server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/scarlet-estoque
    password: lucas123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka

app:
  pasta-fotos: C:\\Users\\lucas\\OneDrive\\Imagens\\Imagens Scarlet\\